services:
  pseudomarkets.security.identityserver.web:
    image: pseudomarkets.security.identityserver.web
    build:
      context: .
      dockerfile: src/PseudoMarkets.Security.IdentityServer.Web/Dockerfile

