// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PseudoMarkets.Shared.Entities.Database;

#nullable disable

namespace PseudoMarkets.Shared.Entities.Migrations
{
    [DbContext(typeof(PseudoMarketsDbContext))]
    partial class PseudoMarketsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.Platform.MarketHolidayEntity", b =>
                {
                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holiday_date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("holiday_name");

                    b.HasKey("HolidayDate");

                    b.ToTable("market_holidays", (string)null);

                    b.HasData(
                        new
                        {
                            HolidayDate = new DateOnly(2026, 1, 1),
                            HolidayName = "New Year's Day"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 1, 19),
                            HolidayName = "Martin Luther King, Jr. Day"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 2, 16),
                            HolidayName = "Washington's Birthday"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 4, 3),
                            HolidayName = "Good Friday"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 5, 25),
                            HolidayName = "Memorial Day"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 6, 19),
                            HolidayName = "Juneteenth National Independence Day"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 7, 3),
                            HolidayName = "Independence Day observed"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 9, 7),
                            HolidayName = "Labor Day"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 11, 26),
                            HolidayName = "Thanksgiving Day"
                        },
                        new
                        {
                            HolidayDate = new DateOnly(2026, 12, 25),
                            HolidayName = "Christmas Day"
                        });
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.ReferenceData.TradingInstrumentEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<double>("ClosingPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("closing_price");

                    b.Property<DateOnly>("ClosingPriceDate")
                        .HasColumnType("date")
                        .HasColumnName("closing_price_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("PrimaryInstrumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_instrument_type");

                    b.Property<string>("SecondaryInstrumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("secondary_instrument_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<bool>("TradingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("trading_status");

                    b.HasKey("Symbol");

                    b.HasIndex("SecondaryInstrumentType");

                    b.HasIndex("TradingStatus");

                    b.ToTable("trading_instruments", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.AccountBalanceEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cash_balance");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("UserId");

                    b.ToTable("account_balances", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.CashMovementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference_id");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("movement_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("cash_movements", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.LedgerTransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<string>("ExternalReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("PostingBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("posting_batch_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_description");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("TransactionKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_kind");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VoidsTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("voids_transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("PostingBatchId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("VoidsTransactionId");

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PositionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostBasisTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_basis_total");

                    b.Property<string>("PositionSide")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("position_side");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Symbol")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PositionLotClosureEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<Guid>("ClosingTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("closing_transaction_id");

                    b.Property<decimal>("CostBasisAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_basis_amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OpeningTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("opening_transaction_id");

                    b.Property<long>("PositionLotId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_lot_id");

                    b.Property<decimal>("QuantityClosed")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity_closed");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClosingTransactionId");

                    b.HasIndex("PositionLotId");

                    b.HasIndex("UserId", "Symbol");

                    b.ToTable("position_lot_closures", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PositionLotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ClosingTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("closing_transaction_id");

                    b.Property<string>("LotEntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lot_entry_type");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<Guid>("OpeningTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("opening_transaction_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<decimal>("QuantityOpened")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity_opened");

                    b.Property<decimal>("QuantityRemaining")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity_remaining");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClosingTransactionId");

                    b.HasIndex("OpeningTransactionId");

                    b.HasIndex("UserId", "Symbol");

                    b.ToTable("position_lots", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PostingBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("posting_batches", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.TradeExecutionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<decimal>("ExecutionPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("execution_price");

                    b.Property<string>("ExternalExecutionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_execution_id");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fees");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<DateOnly>("SettlementDate")
                        .HasColumnType("date")
                        .HasColumnName("settlement_date");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<string>("TradeSide")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trade_side");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalExecutionId")
                        .IsUnique();

                    b.HasIndex("Symbol");

                    b.HasIndex("SettlementDate");

                    b.HasIndex("TradeDate");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("trade_executions", (string)null);
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.LedgerTransactionEntity", b =>
                {
                    b.HasOne("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PostingBatchEntity", "PostingBatch")
                        .WithMany("LedgerTransactions")
                        .HasForeignKey("PostingBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostingBatch");
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PositionLotClosureEntity", b =>
                {
                    b.HasOne("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PositionLotEntity", "PositionLot")
                        .WithMany("Closures")
                        .HasForeignKey("PositionLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionLot");
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PositionLotEntity", b =>
                {
                    b.Navigation("Closures");
                });

            modelBuilder.Entity("PseudoMarkets.Shared.Entities.Entities.TransactionProcessing.PostingBatchEntity", b =>
                {
                    b.Navigation("LedgerTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
