services:
  aerospike:
    image: aerospike:ce-8.1.1.1_1
    container_name: pseudomarkets-nextgen-aerospike
    platform: linux/arm64
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "asinfo -v 'status' | grep -q '^ok$'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ../.docker-data/aerospike:/opt/aerospike/data
      - ../infrastructure/aerospike/aerospike.conf:/opt/aerospike/etc/aerospike.conf:ro
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike.conf"
    restart: unless-stopped

  pseudomarkets.marketdata.service:
    image: pseudomarkets.marketdata.service
    build:
      context: .
      dockerfile: src/PseudoMarkets.MarketData.Service/Dockerfile
    container_name: pseudomarkets-nextgen-marketdata-service
    env_file:
      - ../.env
    depends_on:
      aerospike:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      Aerospike__Host: aerospike
      Aerospike__Port: 3000
    ports:
      - "8081:8081"
    restart: unless-stopped
