service {
    cluster-name pseudo-markets-local
    proto-fd-max 15000
}

logging {
    console {
        context any info
    }
}

network {
    service {
        address any
        access-address 127.0.0.1
        port 3000
    }

    heartbeat {
        mode mesh
        port 3002
        interval 150
        timeout 10
        mesh-seed-address-port 127.0.0.1 3002
    }

    fabric {
        port 3001
    }
}

namespace nsPseudoMarkets {
    replication-factor 1
    default-ttl 0
    stop-writes-sys-memory-pct 90

    storage-engine device {
        file /opt/aerospike/data/nsPseudoMarkets.dat
        filesize 1G
    }
}
